### ISSUE TITLE
java.lang.SecurityException: Missing MODIFY_AUDIO_ROUTING permission

### ISSUE THREAD

**Issue by rowest** [ciffelia/MuteCamera#1]
On my Pixel 5 (Android 11) whenever I try to open a camera app and mute() function is triggered
```
fun mute() {
        try {
            setWiredDeviceConnectionState.invoke(audioManager, DEVICE_OUT_SPEAKER, 0, "", "device1")
            setWiredDeviceConnectionState.invoke(audioManager, DEVICE_OUT_REMOTE_SUBMIX, 1, "", "device2")
            // setWiredDeviceConnectionState.invoke(audioManager, DEVICE_OUT_USB_DEVICE, 1, "", "device3")
        } catch (ex: Exception) {
            ex.printStackTrace()
        }
    }
```
 I receive an error.

```
 W/System.err: java.lang.reflect.InvocationTargetException
 W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
 W/System.err:     at com.ciffelia.mutecamera.DeviceAudio.mute(DeviceAudio.kt:35)
 W/System.err:     at com.ciffelia.mutecamera.service.ForegroundService.handleForegroundAppChange(ForegroundService.kt:59)
 W/System.err:     at com.ciffelia.mutecamera.service.ForegroundService.access$handleForegroundAppChange(ForegroundService.kt:13)
 W/System.err:     at com.ciffelia.mutecamera.service.ForegroundService$appObserver$2$1.invoke(ForegroundService.kt:20)
 W/System.err:     at com.ciffelia.mutecamera.service.ForegroundService$appObserver$2$1.invoke(ForegroundService.kt:13)
 W/System.err:     at com.ciffelia.mutecamera.appusage.ForegroundAppObserver.handleUsageEvent(ForegroundAppObserver.kt:37)
 W/System.err:     at com.ciffelia.mutecamera.appusage.ForegroundAppObserver.access$handleUsageEvent(ForegroundAppObserver.kt:7)
 W/System.err:     at com.ciffelia.mutecamera.appusage.ForegroundAppObserver$eventObserver$1.invoke(ForegroundAppObserver.kt:12)
 W/System.err:     at com.ciffelia.mutecamera.appusage.ForegroundAppObserver$eventObserver$1.invoke(ForegroundAppObserver.kt:7)
 W/System.err:     at com.ciffelia.mutecamera.appusage.UsageEventObserver.fetchNewEvents(UsageEventObserver.kt:52)
 W/System.err:     at com.ciffelia.mutecamera.appusage.UsageEventObserver.access$fetchNewEvents(UsageEventObserver.kt:9)
 W/System.err:     at com.ciffelia.mutecamera.appusage.UsageEventObserver$startObserve$runnable$1.run(UsageEventObserver.kt:31)
 W/System.err:     at android.os.Handler.handleCallback(Handler.java:938)
 W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
 W/System.err:     at android.os.Looper.loop(Looper.java:223)
 W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7660)
 W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
 W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
 W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
 W/System.err: Caused by: java.lang.SecurityException: Missing MODIFY_AUDIO_ROUTING permission
 W/System.err:     at android.os.Parcel.createExceptionOrNull(Parcel.java:2373)
 W/System.err:     at android.os.Parcel.createException(Parcel.java:2357)
 W/System.err:     at android.os.Parcel.readException(Parcel.java:2340)
 W/System.err:     at android.os.Parcel.readException(Parcel.java:2282)
 W/System.err:     at android.media.IAudioService$Stub$Proxy.setWiredDeviceConnectionState(IAudioService.java:3635)
 W/System.err:     at android.media.AudioManager.setWiredDeviceConnectionState(AudioManager.java:4774)
 W/System.err: 	... 20 more
 W/System.err: Caused by: android.os.RemoteException: Remote stack trace:
 W/System.err:     at com.android.server.audio.AudioService.enforceModifyAudioRoutingPermission(AudioService.java:2527)
 W/System.err:     at com.android.server.audio.AudioService.setWiredDeviceConnectionState(AudioService.java:5128)
 W/System.err:     at android.media.IAudioService$Stub.onTransact(IAudioService.java:1656)
 W/System.err:     at android.os.Binder.execTransactInternal(Binder.java:1159)
 W/System.err:     at android.os.Binder.execTransact(Binder.java:1123)
```

As I can see from the stacktrace "android.permission.MODIFY_AUDIO_ROUTING" permission is required for the app to be able to invoke setWiredDeviceConnectionState method from AudioManager class. But the problem is this permission is only granted to system apps, so adding 
`    <uses-permission
        android:name="android.permission.MODIFY_AUDIO_ROUTING"
        android:protectionLevel="signature|privileged" />`
will not work.

Do you have any idea how to solve this issue?

**Comment by ciffelia** [comment]
I'm afraid not.
Since Android 11, `setWiredDeviceConnectionState` method requires `MODIFY_AUDIO_ROUTING` permission which is only granted to system apps. I think it is impossible to bypass this limitation without root access.
